### PR TITLE
Add github action for nodejs & sapper export

### PR DESCRIPTION
**Pull request by clhenrick**
Set up a Github Action that will run on all future PRs. If this isn't helpful we can always adjust or remove it later.

### CODE REVIEW

**Comment by clhenrick** [comment]
Because the `sapper export` command takes a while we may only want to test this on one version of NodeJS, but we might want to agree on what NodeJS version we're using.

**Comment by clhenrick** [comment]
@mukhtyar @elehmer I'm curious as to what version of NodeJS you both are using? I'm on a LTS `14.17.x`

**Comment by mukhtyar** [comment]
`14.17.0` and `14.16.0`. I can update to `14.17.x` if needed.

**Comment by elehmer** [comment]
`12.22.6`...I guess it should be more up-to-date than that? I didn't know what you guys were running so I just got it up to the minimum needed to build. Let me know what versions you are on and I'll update.

**Comment by clhenrick** [comment]
Thanks @mukhtyar @elehmer maybe we can stick with `14.17.x` which is a LTS version of NodeJS. It occasionally helps with bugs if we're all on the same version.

**Comment by elehmer** [comment]
Ubuntu 20.04 gravitated to 14.18.x as its LTS. I'm not going to battle to get to 14.17.x as it shouldn't cause any issues I don't think.

**Pull request merged**
