### PR TITLE
Add v2 links

### PR DESCRIPTION
**Pull request by mukhtyar**
Add links to v2 cal-adapt for some Tools and all Data Download instances

### CODE REVIEW

**Review by clhenrick — APPROVED** [review]
Thanks Shruti, the Local Climate Change Snapshot tool still gives a 404, do we want to fix it in this PR?

**Comment by clhenrick** [comment]
@mukhtyar actually there's one other place where we should fix the data download link, in `content/faqs/how-can-i-download-data-from-caladapt.md`

**Comment by mukhtyar** [comment]
> Thanks Shruti, the Local Climate Change Snapshot tool still gives a 404, do we want to fix it in this PR?

Hmm, I don't see it? The link should be `https://v2.cal-adapt.org/tools/local-climate-change-snapshot/`

**Comment by clhenrick** [comment]
@mukhtyar it must not have finished rebuilding when I checked locally, I see that it points to the v2 domain now.

**Pull request merged**
