### PR TITLE
upgrade deps: svelte, svelte-loader, webpack

### PR DESCRIPTION
**Pull request by clhenrick**
Seems good to upgrade Svelte to the latest version but we should check to see if it breaks anything.

### CODE REVIEW

**Comment by clhenrick** [comment]
@mukhtyar I’m noticing there’s a lot of a11y warnings being outputted in the terminal, seems mostly from hover events on chart SVG elements. It would be good if we could suppress them so that there’s not tons of output in the console each time a (re)build happens

**Review by mukhtyar — APPROVED** [review]

**Comment by mukhtyar** [comment]
@clhenrick created a [new PR](https://github.com/berkeley-gif/caladapt-website-2021/pull/166) to fix the a11y warnings

**Comment by clhenrick** [comment]
@mukhtyar did you take some time to poke around the tools and make sure nothing broke with any of them? I haven't yet but will today, would be good to double check.

**Comment by clhenrick** [comment]
@mukhtyar I also ended up upgrading `svelte-loader` and `webpack`; hopefully this helps make builds a little faster.

**Comment by clhenrick** [comment]
Wait until #166 is merged before merging this PR.

**Pull request merged**
