### PR TITLE
SLR CIS: content updates

### PR DESCRIPTION
**Pull request by clhenrick**
- [x] edit items in resources list
- [x] add images for resources list items
- [x] add "learn more" content

### CODE REVIEW

**Comment by clhenrick** [comment]
[Add image logos for Sea Level Rise resources](https://trello.com/c/FIgBLilA/161-add-image-logos-for-sea-level-rise-resources)

**Comment by clhenrick** [comment]
[SLR CIS: add "learn more" content](https://trello.com/c/4pRmdPaY/164-slr-cis-add-learn-more-content)

**Review by mukhtyar — APPROVED** [review]
Looks good! Separating out the Learn More content into markdown files make a lot of sense.

**Comment by clhenrick** [comment]
> Looks good! Separating out the Learn More content into markdown files make a lot of sense.

@mukhtyar thanks, and strangely it seems to prevent it from being bundled in with the JS.

**Pull request merged**
