### PR TITLE
bug fix: static map boundary overlay

### PR DESCRIPTION
**Pull request by clhenrick**
Uses a revamped version of the `StaticMap` component which does not rely on using TurfJS to simplify a geometry prior to rendering it (which would frequently create invalid geometries for more complex polygons).

Replaced all instances of the previous `StaticMap` component with a `LocationMap` component that wraps the new `StaticMap` component from [`@berkeley-gif/cal-adapt-svelte-components`](https://github.com/berkeley-gif/cal-adapt-svelte-components) to handle responsiveness and keep the aspect ratio consistent.

### CODE REVIEW

**Comment by clhenrick** [comment]
[Bug: tool locator map fails to load due to invalid polygon](https://trello.com/c/cKnxzgSN/196-bug-tool-locator-map-fails-to-load-due-to-invalid-polygon)

**Comment by clhenrick** [comment]
@elehmer please take a look at any of the following tools and try selecting a location with a complex geometry (such as counties in northern CA) and tools that use the "station" location type:

- [ ] Annual Averages
- [ ] Degree Days
- [ ] Extended Drought
- [ ] Extreme Heat
- [ ] Extreme Precipitation
- [ ] Extreme Weather
- [ ] Snowpack
- [ ] Streamflow
- [ ] Wildfire

Netlify preview deploy: https://bug-fix-static-map--happy-engelbart-4042ee.netlify.app/tools/

**Review by elehmer — APPROVED** [review]
LGTM! I did notice 2 warnings on in the browser console:

1. Vector tile source "counties" layer "county" does not use vector tile spec v2 and therefore may have some rendering errors.

2. Geometry exceeds allowed extent, reduce your vector tile buffer size

**Comment by clhenrick** [comment]
@elehmer thanks, those warnings are from MapBoxGLJS and don't relate to the Location Map component.

**Pull request merged**
